### ISSUE TITLE
Makefile install target contains version

### ISSUE THREAD

**Issue by inglor** [makedumpfile/makedumpfile#10]
Hi,

Why does the install target path contains the $Version information on the below lines?

https://github.com/makedumpfile/makedumpfile/blob/master/Makefile#L133-L135

Subsequent question: Are these `eppic_script` useful to non Fedora systems (like Archlinux) ?

**Comment by k-hagio** [comment]
> Why does the install target path contains the $Version information on the below lines?
> 
> https://github.com/makedumpfile/makedumpfile/blob/master/Makefile#L133-L135

41e1ccf introduced those lines with `${VERSION}`. I'm not sure, but supposedly no big reason.
If you would like to remove it, please post a patch to the mailing list.

> Subsequent question: Are these `eppic_script` useful to non Fedora systems (like Archlinux) ?

I'm not familiar with other distributions than Fedora/RHEL, but I think that you can use
the eppic function if you like and they are also example scripts to use it.

**Comment by inglor** [comment]
@k-hagio Sent - thanks.
