### ISSUE TITLE
makedumpfile Add dmesg PRINTK_CALLER id support

### ISSUE THREAD

**Issue by egchron** [makedumpfile/makedumpfile#13]
Overview: The Linux Kernel added support for a PRINTK_CALLER id field to be added to dmesg entries in the kernel ring buffer.
                   This field provides the thread id or the CPU id (if CPU context) that issued the printk that added the message to the
                   ring buffer. That id information is very helpful for debugging. Support to print the caller-id field if present was added 
                   to the util-linux sys-utils dmesg command (both SYSLOG and kmsg interfaces).
                   Support for printing the caller id if present would be very helpful to have with makedumpfile so that is what this
                   patch added.

Sent patch to the mailing list as recommended.

**Comment by egchron** [comment]
Testing of makedumpfile with the enhancement provided by the patch for makedumpfile Issue #13

We need to test the two versions (out of three) of the log/demsg ringbuffer that have support for PRINTK_CALLER.

The PRINTK_CALLER was added with Linux-5.1 to printk-log and the caller-id field is conditionally compiled in
so older versions the kernel and versions 5.1 through 5.9 without CONFIG_PRINT_CALLER configured will not
include the caller_id field.

With Linux-5.10 the Linux kernel switched to lockless printk-info structure.
That structure always has caller_id present whether PRINTK_CALLER is defined or not (not conditionally compiled out)
and it is always filled in by the kernel. So this means that the field will always be present in /proc/vmcore and 
so makedumpfile can access it with correct values in all kernels 5.10 and later. For those kernels not configuring
PRINTK_CALLER just means that the caller_id field is not displayed by dmesg. This because both the old SYSLOG
interface and the newer kmsg interface won't present the caller_id value in their user interfaces.
This is important to realize as with 5.10 and later kernels PRINTK_CALLER will always be present with the
makedumpfile --dump-dmesg command.

These test the two versions of the log/dmesg ringbuffer that support PRINTK_CALLER: printk_log and printk_info.

These are gzip'ed test file output files, two files each from two different kernels:

* Linux-5.4.264 kernel which use the printk_log version of log/dmesg ringbuffer that we want to test.
  -------------------------------------------------------------------------------------------------------------------------------------------------
   Two files provided:
    1) Linux-5.4.264 with CONFIG_PRINTK_CALLER not configured
        in this case the PRINTK_CALLER field is not defined by the Linux Kernel (printk_log structure) so it can't be
        picked in vmcore produced by makedumpfile and makedumpfile --dump-dmesg will not print any additional field
        since the caller_id field in printk_log is not present in this case.
    2) Linux 5.4.364 with CONFIG_PRINTK_CALLER is configured
        in this case the PRINTK_CALLER field is defined by the Linux Kernel (printk_log strucutre) so it is present in the
       vmcore produced by makedumpfile and makedumpfile --dump-dmesg prints the caller_id field following the time
       stamp in the log/dmesg record.

Note: Format of log / dmesg records is consistent with dmesg -S and dmesg format when PRINTK_CALLER is defined
           It follows the time stamp and is preceded by a space unless the timestamp is omitted in which case it is the
           first field both dmesg and dmesg -P displays.

Test output files:
-----------------------

Test output: makedumpfile --dump-dmesg on a Linux-5.4.264 Kernel with PRINTK_CALLER not set (not configured)
As expected dmesg output has no PRINTK_CALLER field because ring buffer for kernels > 3.11 and < 5.10 the
printk_log structure has PRINTK_CALLER conditionally defined so it is not available if PRINTK_CALLER is not configured
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[linux-5.4.264_no_printk_caller_makdumpfile_dmesg.txt.gz](https://github.com/makedumpfile/makedumpfile/files/13734166/linux-5.4.264_no_printk_caller_makdumpfile_dmesg.txt.gz)

Test output: makedumpfile --dump-dmesg on a Linux-5.4.264 Kernel with PRINTK_CALLER is set (configured)
As expected the PRINTK_CALLER field prints after the time stamp
This because PRINTK_CALLER field is defined and filled in so makedumpfile now prints it.
----------------------------------------------------------------------------------------------------------------------------------
[linux-5.4.264_printk_caller_makdumpfile_dmesg.txt.gz](https://github.com/makedumpfile/makedumpfile/files/13734211/linux-5.4.264_printk_caller_makdumpfile_dmesg.txt.gz)

* Linux-6.6.6 kernel which uses the printk_info version of tje log/dmesg ringbuffer that we want to test.
  ----------------------------------------------------------------------------------------------------------------------------------------------------
Two files provided:
1) Linux-6.6.6 with CONFIG_PRINTK_CALLER not configured
    with printk_info used in 5.10 Kernels the caller_id is always present and filled in so we get valid values for caller_id
    even though CONFIG_PRINTK_CALLER is not set
2) Linux-6.6.6 with CONFIG_PRINTK_CALLER is configured
    with printk_info used in 5.10 Kernels the caller_id is always present and filled in so we get valid values for caller_id
    as expected.

Test output: makedumpfile --dump-dmesg on a Linux-6.6.6 Kernel with PRINTK_CALLER not set (not configured)
As expected, even though PRINTK_CALLER is not configured it is present and valid in printk_info such that
makedumpfile picks up the caller_id field and prints it. 
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
[linux-6.6.6_no_printk_caller_makedumpfile_dmesg.txt.gz](https://github.com/makedumpfile/makedumpfile/files/13734439/linux-6.6.6_no_printk_caller_makedumpfile_dmesg.txt.gz)

Test output: makedumpfile --dump-dmesg on a Linux-6.6.6 Kernel with PRINTK_CALLER is set (configured)
As expected the PRINTK_CALLER field prints after the time stamp
-----------------------------------------------------------------------------------------------------------------------------------------------------------
[linux-6.6.6_printk_caller_makedumpfile_dmesg.txt.gz](https://github.com/makedumpfile/makedumpfile/files/13734437/linux-6.6.6_printk_caller_makedumpfile_dmesg.txt.gz)

---------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by egchron** [comment]
Sorry, not sure why some of the lines above were in a larger bold font.

**Comment by k-hagio** [comment]
Thank you, I've replied to your email, could you update the patch and post again?

**Comment by egchron** [comment]
Posted revised patch.

**Comment by egchron** [comment]
Posted revised patch.

**Comment by egchron** [comment]
Just for reference, here is the most recent version of the patch posted to the makedumpfile mailing list:

[makedumpfile-add-dmesg-PRINTK_CALLER-id-support-rev3.patch.gz](https://github.com/makedumpfile/makedumpfile/files/13757017/makedumpfile-add-dmesg-PRINTK_CALLER-id-support-rev3.patch.gz)

**Comment by egchron** [comment]
Here is the intial version of the crash utility patch that provide log / dmesg support for the printk caller field.
This issue is covered by crash utlity Issue #164
        crash utility: add log / dmesg PRINTK_CALLER id support

I posted the current version of the makedumpfile patch to crash utility Issue 164 to make it avalable for testing.

Without makedumpfile support for PRINTK_CALLER caller_id the crash utility will not be able to display the caller_id field for dmesgs for vmcore files.

Posting the crash utility patch here to make the crash log -P command available here for testing.
The crash help log command documents what the -P option adds and also shows sample output.

[crash-add-log-dmesg-PRINTK_CALLER-id-support-rev0.patch.gz](https://github.com/makedumpfile/makedumpfile/files/13757025/crash-add-log-dmesg-PRINTK_CALLER-id-support-rev0.patch.gz)

**Comment by egchron** [comment]
Here are test results for both makedumpfile --dump-dmesg and for the crash utility for the log -P option that the patch that adds the caller_id field to the log records printed if the log caller_id field is present in the dump.

In addition to the patch submitted for this issue I have submitted a patch to crash utility upstream that I attached in the previous comment, or you can pull it from crash utility Issue 164.  It provides PRINTK_CALLER id support for the crash utility in the form of the log -P or dmesg -P option. 

This makedumpfile patch is needed to test the crash facility since to provides the support to produce vmcore files that include the caller_id field for log records. That is what crash needs to provide the caller_id for log / dmesg records if requested.

So that is why I also include output from makedumpfie --dump-dmesg so that you can compare the makedumpfile output for the makedumpfile --dump-dmesg command versus the output crash log -P produces to print out the dmesg records.

Note that I tested and provide results for two Linux Kernels: linux-5.4.256 and linux-6.6.6

The reason for this is to cover the two versions of the Linux kernel ringbuffer that provide PRINTK_CALLER support the versions for printk_log and printk_info.

There are two versions because PRINTK_CALLER id support as provided by the CONFIG_PRINTK_CALLER kernel configuration parameter that was added in Linux-5.1 which is using the printk_log internal structure. The newer printk_caller structure used by the lockless ringbuffer was added in Linux 5.10 and has been in use ever since and this structure replaced the older printk_log structure with the printk_info structure.

So Linux-5.4.264 covers the older printk_log internal structure format and Linux-6.6.6 covers the newer printk_info internal structure format of the Linux ringbuffer.

Here are output files created using the crash patch posted here and in crash utility Issue-164 and also in the crash utility mailing list and using our latest makedumpfile patch here (revision-3).

Using the latest revision-3 patch to enhance makedumpfile 1.7.4++ output: makedumpfile --dump-dmesg and using the current latest revision-0 of the crash utility Issue-164 patch.

For Linux Kernel 5.4.264 with PRINTK_CALLER configured:

The makedumpfile --dump-dmesg output:

[test-makedumpfile-dump-dmesg-v5.4.264_CONFIG_PRINTK_CALLER.txt.gz](https://github.com/makedumpfile/makedumpfile/files/13757174/test-makedumpfile-dump-dmesg-v5.4.264_CONFIG_PRINTK_CALLER.txt.gz)

The crash utility: log -P output

[testing_crash_linux-5.4.264-with_CONFIG_PRINTK_CALLER.txt.gz](https://github.com/makedumpfile/makedumpfile/files/13757177/testing_crash_linux-5.4.264-with_CONFIG_PRINTK_CALLER.txt.gz)

For Linux Kernel 6.6.6 with PRINTK_CALLER configured:

The makedumpfile --dump-dmesg output:

[test-makedumpfile-dump-dmesg-v6.6.6.txt.gz](https://github.com/makedumpfile/makedumpfile/files/13757184/test-makedumpfile-dump-dmesg-v6.6.6.txt.gz)

The crash utility: log -P output

[testing_crash_linux-6.6.6.txt.gz](https://github.com/makedumpfile/makedumpfile/files/13757189/testing_crash_linux-6.6.6.txt.gz)

These files can also be found with crash utlity Issue-164

This output is generated using the latest versions of the patches for both:
makedumpfile Issue-13  and crash utility Issue-164
as of 2023/12/22 14:00 PST

**Comment by egchron** [comment]
I wanted to ensure I match up with the recommended code so posting to make sure I am synch.
Here is the revised makedump patch that includes the few small changes you recommended:

[makedumpfile-add-dmesg-PRINTK_CALLER-id-support-rev4.patch.gz](https://github.com/makedumpfile/makedumpfile/files/13789208/makedumpfile-add-dmesg-PRINTK_CALLER-id-support-rev4.patch.gz)

This is the latest revision to the util-linux dmesg code:

[util-linux-sys-utils-dmesg-2609-rev5.patch.gz](https://github.com/makedumpfile/makedumpfile/files/13789229/util-linux-sys-utils-dmesg-2609-rev5.patch.gz)

This patch applies to the latest util-linux git hub code pull.

This has the correct caller_id spacings and yes they allow 8 characters for the dmesg kmsg version of caller_id and 6 characters for the SYSLOG version which is consistent with the PID_MAX_LIMIT. Note those are 1 character for the T or C and either 7 characters or 5 characters for the id numbers for each of the respective dmesg interface types.   

Note on the dmesg patch it applies but does make some noise related to util-linux test files that are needed:

[echron@catalina util-linux]$ patch -b -p 1 --dry-run -i /home/echron/util-linux-sys-utils-dmesg-2609-rev5.patch.
checking file include/pathnames.h
checking file sys-utils/dmesg.c
checking file tests/expected/dmesg/colors-kmsg-printk-caller
checking file tests/expected/dmesg/console-levels-kmsg-printk-caller
checking file tests/expected/dmesg/decode-kmsg-printk-caller
checking file tests/expected/dmesg/delta-kmsg-printk-caller
checking file tests/expected/dmesg/facilities-kmsg-printk-caller
checking file tests/expected/dmesg/indentation-kmsg-printk-caller
checking file tests/expected/dmesg/json-kmsg-printk-caller
checking file tests/expected/dmesg/json-syslog-printk-caller
checking file tests/expected/dmesg/kmsg-file-printk-caller
checking file tests/expected/dmesg/limit-kmsg-printk-caller
checking file tests/ts/dmesg/colors-kmsg-printk-caller
checking file tests/ts/dmesg/console-levels-kmsg-printk-caller
checking file tests/ts/dmesg/decode-kmsg-printk-caller
checking file tests/ts/dmesg/delta-kmsg-printk-caller
checking file tests/ts/dmesg/facilities-kmsg-printk-caller
checking file tests/ts/dmesg/indentation-kmsg-printk-caller
checking file tests/ts/dmesg/input-syslog-printk-caller
checking file tests/ts/dmesg/json-kmsg-printk-caller
checking file tests/ts/dmesg/json-syslog-printk-caller
checking file tests/ts/dmesg/kmsg-file-printk-caller
File tests/ts/dmesg/kmsg-input-printk-caller: git binary diffs are not supported.
checking file tests/ts/dmesg/limit-kmsg-printk-caller
File tests/ts/dmesg/newlines-kmsg-printk-caller: git binary diffs are not supported.

**Comment by egchron** [comment]
Here are the updated dmesg patches that include the PRINTK_CALLER id support and all the tests that I've added to support testing the both dmesg interfaces for syslog and kmsg. I also added standard (non PRINTK_CALLER id) kmsg interface tests because for some reason they were missing with the dmesg tests and are needed.

To work around the git format-patch issue with multiple binary files in a patch (it doesn't handle a second binary file correctly) I split the patch for util-linux dmesg Issue: #2663 into two patches, that resolves the problem.

You can also pull the files from the util-linux mailing list Issue #2666 which is just a merge of Issue #2609, #2637 and #2663 .

These separate issues are just patches for the dmesg PRINTK_CALLER id code and tests (#2609), tests for the dmesg syslog interface for PRINTK_CALLER that were missing (even though it was supported, #2637) and standard dmesg kmsg interface tests which were also missing (#2663). Applying the patches in the order specified produces all the test ouput needed to verify that the kmsg and syslog interfaces work correctly as do the comparable tests for the caller-Id versions of the tests.

You will note that dmesg spacing for the printk caller_id field is consistent with what we have for makedumpfile with a character for the thread or CPU identifier and 7 characters to hold up to 7 digits of thread id.

You can also pull the patches from the util-linux mailing list or the util-linux githib website. See Issue #2666

[util-linux-dmesg-issue-2666-patch-1.patch.gz](https://github.com/makedumpfile/makedumpfile/files/13801999/util-linux-dmesg-issue-2666-patch-1.patch.gz)
[util-linux-dmesg-issue-2666-patch-2.patch.gz](https://github.com/makedumpfile/makedumpfile/files/13802000/util-linux-dmesg-issue-2666-patch-2.patch.gz)
[util-linux-dmesg-issue-2666-patch-3.patch.gz](https://github.com/makedumpfile/makedumpfile/files/13802001/util-linux-dmesg-issue-2666-patch-3.patch.gz)
[util-linux-dmesg-issue-2666-patch-4.patch.gz](https://github.com/makedumpfile/makedumpfile/files/13802002/util-linux-dmesg-issue-2666-patch-4.patch.gz)

**Comment by egchron** [comment]
Just FYI, The upstreamed patch for util-linux-dmesg-issue-2666-patch-1.patch was revised. 

It need to be retrofitted since a dmesg timestamp enhancement that a colleague of Ivan's and mine submitted to enchance dmesg timestamps has merged. 

I also revised the the expected results of cid-kmsg (caller_id kmsg dmesg tests) to normalize output test output to be consistent regardless of what Linux settings are for /proc/sys/kernel/pid_max. This so expected test results always match.

No functional code changes to the actual dmesg code were needed for this, but these patches can applied to the latest version of util-linux for testing if you are interested.

See util-linux Issue: #2666 for details.

[util-linux-dmesg-issue-2666-patch-1-rev1.patch.gz](https://github.com/makedumpfile/makedumpfile/files/13846864/util-linux-dmesg-issue-2666-patch-1-rev1.patch.gz)
[util-linux-dmesg-issue-2666-patch-2-rev1.patch.gz](https://github.com/makedumpfile/makedumpfile/files/13846865/util-linux-dmesg-issue-2666-patch-2-rev1.patch.gz)
[util-linux-dmesg-issue-2666-patch-3-rev1.patch.gz](https://github.com/makedumpfile/makedumpfile/files/13846866/util-linux-dmesg-issue-2666-patch-3-rev1.patch.gz)
[util-linux-dmesg-issue-2666-patch-4-rev1.patch.gz](https://github.com/makedumpfile/makedumpfile/files/13846867/util-linux-dmesg-issue-2666-patch-4-rev1.patch.gz)

**Comment by egchron** [comment]
Here are the revisions that Kazu has requested per his note on Friday January 19th.

[crash-add-log-dmesg-PRINTK_CALLER-id-support-rev2.patch.gz](https://github.com/makedumpfile/makedumpfile/files/14002130/crash-add-log-dmesg-PRINTK_CALLER-id-support-rev2.patch.gz)

**Comment by egchron** [comment]
FYI, as mentioned in the crash utility Issues.

The util-linux folks have merged the dmesg upgrade to support caller_id with the dmesg
/dev/kmsg interface so now there is support for PRINTK_CALLER caller_id for both SYSLOG
and default dmesg format.

Thank you,

Edward
