### ISSUE TITLE
6.11 support

### ISSUE THREAD

**Issue by jfernandez** [makedumpfile/makedumpfile#14]
I'm debugging a 6.11-RC crash and haven't been able to get a core dump that works correctly on either `crash` or `drgn`. The issue seems to be missing pages in the dump.

I'm currently using a patched `makedumpfile` with these 6.9 and 6.10 fixes:
https://github.com/makedumpfile/makedumpfile/commit/985e575253f1c2de8d6876cfe685c68a24ee06e1
https://github.com/makedumpfile/makedumpfile/commit/bad2a7c4fa75d37a41578441468584963028bdda

Could this be an unreported issue with 6.11?

drgn thread: https://github.com/osandov/drgn/issues/421

**Comment by k-hagio** [comment]
Is the issue different from [1]?
[1] https://lists.crash-utility.osci.io/archives/list/devel@lists.crash-utility.osci.io/thread/LMIMWVBXWKG6TSYGIYGDONLPCG54XICA/

If it's different,
- what is the makdumpfile command line you run?
- is your machine x86_64?
- what error is emitted by crash?

**Comment by k-hagio** [comment]
no reply, so closing.
