### ISSUE TITLE
6.12 support

### ISSUE THREAD

**Issue by davidhildenbrand** [makedumpfile/makedumpfile#16]
In 6.12 we got yet another rework of page types stored in _mapcount.

```
commit 4ffca5a96678c9fe1a39ec1e9c8fd326b57ea8a7
Author: Matthew Wilcox (Oracle) <willy@infradead.org>
Date:   Wed Aug 21 18:39:11 2024 +0100

    mm: support only one page_type per page
    
    By using a few values in the top byte, users of page_type can store up to
    24 bits of additional data in page_type.  It also reduces the code size as
    (with replacement of READ_ONCE() with data_race()), the kernel can check
    just a single byte. 
```

Using makedumpfile on a 6.12 kernel, I can see that no pages are detected as free (buddy) and offline -- where there should be some.

I suspect the whole "PAGE_TYPE_BASE" logic is now wrong and makes isSlab() report false positives all of the time.

With newer kernels, we really should be using PAGE_BUDDY_MAPCOUNT_VALUE/PAGE_SLAB_MAPCOUNT_VALUE/PAGE_HUGETLB_MAPCOUNT_VALUE as the actual value of "_mapcount" and not try deriving flags from it.

**Comment by davidhildenbrand** [comment]
Indeed, it starts working again as expected with

```
diff --git a/makedumpfile.c b/makedumpfile.c
index b356eb3..bad3c48 100644
--- a/makedumpfile.c
+++ b/makedumpfile.c
@@ -280,8 +280,7 @@ isSlab(unsigned long flags, unsigned int _mapcount)
 {
 	/* Linux 6.10 and later */
 	if (NUMBER(PAGE_SLAB_MAPCOUNT_VALUE) != NOT_FOUND_NUMBER) {
-		unsigned int PG_slab = ~NUMBER(PAGE_SLAB_MAPCOUNT_VALUE);
-		if ((_mapcount & (PAGE_TYPE_BASE | PG_slab)) == PAGE_TYPE_BASE)
+		if (_mapcount == (int)NUMBER(PAGE_SLAB_MAPCOUNT_VALUE))
 			return TRUE;
 	}
 
@@ -6549,11 +6548,10 @@ __exclude_unnecessary_pages(unsigned long mem_map,
 			 */
 			if (NUMBER(PAGE_HUGETLB_MAPCOUNT_VALUE) != NOT_FOUND_NUMBER) {
 				unsigned long _flags_1 = ULONG(addr + OFFSET(page.flags));
-				unsigned int PG_hugetlb = ~NUMBER(PAGE_HUGETLB_MAPCOUNT_VALUE);
 
 				compound_order = _flags_1 & 0xff;
 
-				if ((_mapcount & (PAGE_TYPE_BASE | PG_hugetlb)) == PAGE_TYPE_BASE)
+				if (_mapcount == (int)NUMBER(PAGE_HUGETLB_MAPCOUNT_VALUE))
 					compound_dtor = IS_HUGETLB;
 
 				goto check_order;
diff --git a/makedumpfile.h b/makedumpfile.h
index 7ed566d..2b3495e 100644
--- a/makedumpfile.h
+++ b/makedumpfile.h
@@ -164,8 +164,6 @@ test_bit(int nr, unsigned long addr)
 #define isAnon(mapping, flags, _mapcount) \
 	(((unsigned long)mapping & PAGE_MAPPING_ANON) != 0 && !isSlab(flags, _mapcount))
 
-#define PAGE_TYPE_BASE		(0xf0000000)
-
 #define PTOB(X)			(((unsigned long long)(X)) << PAGESHIFT())
 #define BTOP(X)			(((unsigned long long)(X)) >> PAGESHIFT())
 
-- 
2.46.1
```

The lower 24bit of the page_type (_mapcount) can be reused by the page owner, however currently only zsmalloc does that. A more future proof (at least near future) approach would be to expose a mask to apply on top of _mapcount, sow e could mask these (currently) 24bit out.

**Comment by k-hagio** [comment]
Thank you for the information.

> Using makedumpfile on a 6.12 kernel, I can see that no pages are detected as free (buddy) and offline -- where there should be some.

I confirmed it, but still have not been able to have time to think about a solution enough.
```
$ makedumpfile -d 31 --show-stats vmcore dump.d31
...
    Free pages              : 0x0000000000000000
```
Is it possible to create a makedumpfile patch for it?

**Comment by davidhildenbrand** [comment]
I can post the fix upstream, only might take a couple of days until I get to it.

**Comment by k-hagio** [comment]
@davidhildenbrand
is there any progress on your side?

**Comment by davidhildenbrand** [comment]
Got distracted, composing the patch description now ... :)

**Comment by davidhildenbrand** [comment]
https://lkml.kernel.org/r/20241122101219.936746-1-david@redhat.com

**Comment by k-hagio** [comment]
Thank you for posting the patch! I will review and test it.

**Comment by k-hagio** [comment]
Closing with 72c3414949bd2e9284c8ba7ceaf109a5a34ac2e1.
