### ISSUE TITLE
makedumpfile to create core for MIPS 

### ISSUE THREAD

**Issue by Kullu14** [makedumpfile/makedumpfile#6]
I am trying to use makedumpfile tool for MIPS architecture to collect the core 

In 5.4 kernel after below patch got committed 
https://patchwork.kernel.org/project/linux-mips/patch/20201203123649.44046-1-alexander.sverdlin@nokia.com/#23820103 

I see an issue creating core file with makedumpfile 

vaddr_to_paddr_mips64: Could not translate vaddr: 
readmem: Can't convert a virtual address to physical address.

Anybody has seen the similar issue with MIPS?

**Comment by k-hagio** [comment]
Can you subscribe and post it to the kexec mailing list?
http://lists.infradead.org/mailman/listinfo/kexec

Probably there is no MIPS user here :-)

**Comment by Kullu14** [comment]
Will ask there so closing it here
