### ISSUE TITLE
Feature request: RISCV64 support

### ISSUE THREAD

**Issue by Avimitin** [makedumpfile/makedumpfile#8]
Currently this program can't be compiled on riscv64 machine due to symbol `KVBASE` missing. It would be great if you could implement riscv64 support.

**Comment by k-hagio** [comment]
I've seen some RISC-V people on kexec mailing list [1], so I think probably patches for makedumpfile will also be posted in the near future, but I don't have any information about the plan.

[1] http://lists.infradead.org/mailman/listinfo/kexec

**Comment by k-hagio** [comment]
I forgot to close this with f777afbd7996d0aba7861f437b79f4dd7ab23019, closing.

**Comment by Avimitin** [comment]
Thx!
